# Generated by Django 4.2.23 on 2025-06-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0004_alter_debatesession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debatesession',
            options={},
        ),
        migrations.AlterModelOptions(
            name='debatevote',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moderationaction',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='debatesession',
            name='debates_deb_status_b8ed92_idx',
        ),
        migrations.RemoveIndex(
            model_name='debatesession',
            name='debates_deb_moderat_a0994a_idx',
        ),
        migrations.RemoveIndex(
            model_name='debatevote',
            name='debates_deb_session_4da52a_idx',
        ),
        migrations.RemoveIndex(
            model_name='debatevote',
            name='debates_deb_voter_i_0ee32f_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='debates_mes_session_4c5a38_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='debates_mes_author__29beb9_idx',
        ),
        migrations.RemoveIndex(
            model_name='moderationaction',
            name='debates_mod_session_6d9c5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='moderationaction',
            name='debates_mod_target__c11269_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='debates_not_recipie_3e5df1_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='debates_not_notific_da2401_idx',
        ),
        migrations.RemoveIndex(
            model_name='participation',
            name='debates_par_session_778d1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='participation',
            name='debates_par_user_id_5ef6e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='debates_use_reputat_13a611_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='debates_use_total_d_7c07ca_idx',
        ),
        migrations.RemoveField(
            model_name='debatevote',
            name='best_argument_message',
        ),
        migrations.AlterField(
            model_name='debatesession',
            name='debate_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debatesession',
            name='debate_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debatesession',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='debatesession',
            name='joining_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debatesession',
            name='scheduled_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='debatesession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('joining', 'Joining Window'), ('active', 'Active Debate'), ('voting', 'Voting Period'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='debatesession',
            name='voting_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debatesession',
            name='voting_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debatesession',
            name='winner_side',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='debatevote',
            name='vote',
            field=models.CharField(choices=[('participant_a', 'Participant A Won'), ('participant_b', 'Participant B Won'), ('tie', 'Tie')], max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='action',
            field=models.CharField(choices=[('mute', 'Mute'), ('unmute', 'Unmute'), ('remove', 'Remove'), ('warn', 'Warn'), ('kick', 'Kick')], max_length=10),
        ),
        migrations.AlterField(
            model_name='participation',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
