# Generated by Django 4.2.23 on 2025-06-25 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "debates",
            "0005_alter_debatesession_options_alter_debatevote_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="debatesession",
            old_name="debate_ended_at",
            new_name="actual_start_time",
        ),
        migrations.RenameField(
            model_name="debatesession",
            old_name="debate_started_at",
            new_name="debate_end_time",
        ),
        migrations.RenameField(
            model_name="debatesession",
            old_name="voting_ended_at",
            new_name="joining_window_end",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_system_message",
        ),
        migrations.AddField(
            model_name="debatesession",
            name="max_duration_minutes",
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name="debatesession",
            name="min_duration_minutes",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="debatesession",
            name="voting_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="debatetopic",
            name="category",
            field=models.CharField(
                choices=[
                    ("politics", "Politics"),
                    ("technology", "Technology"),
                    ("education", "Education"),
                    ("environment", "Environment"),
                    ("healthcare", "Healthcare"),
                    ("economics", "Economics"),
                    ("social", "Social Issues"),
                    ("science", "Science"),
                    ("entertainment", "Entertainment"),
                    ("sports", "Sports"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="debatevote",
            name="best_argument_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vote_selections",
                to="debates.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="debatesession",
            name="scheduled_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="debatesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("offline", "Offline"),
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("online", "Online"),
                    ("voting", "Voting"),
                    ("finished", "Finished"),
                    ("cancelled", "Cancelled"),
                ],
                default="offline",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="debatevote",
            name="vote",
            field=models.CharField(
                choices=[
                    ("side_a", "Side A Won"),
                    ("side_b", "Side B Won"),
                    ("tie", "Tie"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Message"),
                    ("system", "System Message"),
                    ("join", "User Joined"),
                    ("leave", "User Left"),
                    ("image", "Image Message"),
                ],
                default="text",
                max_length=20,
            ),
        ),
    ]
