# Generated by Django 4.2.23 on 2025-06-28 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("debates", "0010_add_vote_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="session",
        ),
        migrations.AlterModelOptions(
            name="debatesession",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Debate Session",
                "verbose_name_plural": "Debate Sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="debatetopic",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Debate Topic",
                "verbose_name_plural": "Debate Topics",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["timestamp"],
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="moderationaction",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Moderation Action",
                "verbose_name_plural": "Moderation Actions",
            },
        ),
        migrations.AlterModelOptions(
            name="participation",
            options={
                "verbose_name": "Participation",
                "verbose_name_plural": "Participations",
            },
        ),
        migrations.AlterModelOptions(
            name="sessiontranscript",
            options={
                "verbose_name": "Session Transcript",
                "verbose_name_plural": "Session Transcripts",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.RenameField(
            model_name="sessiontranscript",
            old_name="summary",
            new_name="formatted_content",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="total_debates_participated",
            new_name="debates_participated",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="total_debates_won",
            new_name="debates_won",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="total_messages_sent",
            new_name="messages_sent",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="total_votes_cast",
            new_name="total_votes_received",
        ),
        migrations.RemoveField(
            model_name="message",
            name="author",
        ),
        migrations.RemoveField(
            model_name="participation",
            name="has_voted",
        ),
        migrations.AddField(
            model_name="debatetopic",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The moderator who created this topic",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_topics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="flagged_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="is_system_message",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="reactions_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="debates.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moderationaction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moderationaction",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moderationaction",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="moderationaction",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="moderationaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="participation",
            name="arguments_made",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participation",
            name="is_participant",
            field=models.BooleanField(
                default=False, help_text="True if actively participating"
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="participation",
            name="questions_asked",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="participation",
            name="words_spoken",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sessiontranscript",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sessiontranscript",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessiontranscript",
            name="processing_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessiontranscript",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessiontranscript",
            name="total_messages",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sessiontranscript",
            name="total_participants",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sessiontranscript",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sessiontranscript",
            name="word_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ban_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="push_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_online_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="warnings_received",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="debatesession",
            name="debate_end_time",
            field=models.DateTimeField(
                blank=True, help_text="When debate will/did end", null=True
            ),
        ),
        migrations.AlterField(
            model_name="debatesession",
            name="debate_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When debate chat was unlocked", null=True
            ),
        ),
        migrations.AlterField(
            model_name="debatesession",
            name="joining_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When joining window opened (5 min window)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="debatesession",
            name="joining_window_end",
            field=models.DateTimeField(
                blank=True, help_text="When joining window closes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="debatesession",
            name="scheduled_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional scheduled start time for the session",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="debatesession",
            name="voting_end_time",
            field=models.DateTimeField(
                blank=True, help_text="When voting period ended", null=True
            ),
        ),
        migrations.AlterField(
            model_name="debatesession",
            name="voting_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When 30-second voting period started", null=True
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("system", "System"),
                    ("announcement", "Announcement"),
                    ("reaction", "Reaction"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="moderationaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("warn", "Warning"),
                    ("mute", "Mute"),
                    ("unmute", "Unmute"),
                    ("remove", "Remove Participant"),
                    ("ban", "Ban User"),
                    ("timeout", "Timeout"),
                    ("force_phase_transition", "Force Phase Transition"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="moderationaction",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_actions_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("proposition", "Proposition"), ("opposition", "Opposition")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sessiontranscript",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="sessiontranscript",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_transcripts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("debate_session", "user")},
        ),
        migrations.DeleteModel(
            name="DebateVote",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.CreateModel(
            name="DebateVote",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("debates.vote",),
        ),
    ]
