# Generated by manual fix on 2025-06-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debates", "0012_fix_schema"),
    ]

    operations = [
        # Add missing columns to existing tables
        migrations.RunSQL(
            """
            -- Add missing columns to debates_moderationaction
            DO $$ 
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_moderationaction' 
                             AND column_name='is_active') THEN
                    ALTER TABLE debates_moderationaction 
                    ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_moderationaction' 
                             AND column_name='expires_at') THEN
                    ALTER TABLE debates_moderationaction 
                    ADD COLUMN expires_at TIMESTAMP WITH TIME ZONE;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_moderationaction' 
                             AND column_name='severity') THEN
                    ALTER TABLE debates_moderationaction 
                    ADD COLUMN severity VARCHAR(10) NOT NULL DEFAULT 'medium' 
                    CHECK (severity IN ('low', 'medium', 'high', 'critical'));
                END IF;
            END $$;
            """,
            reverse_sql="-- Cannot reverse",
        ),
        migrations.RunSQL(
            """
            -- Add missing columns to debates_message
            DO $$ 
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_message' 
                             AND column_name='likes_count') THEN
                    ALTER TABLE debates_message 
                    ADD COLUMN likes_count INTEGER NOT NULL DEFAULT 0;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_message' 
                             AND column_name='reactions_count') THEN
                    ALTER TABLE debates_message 
                    ADD COLUMN reactions_count INTEGER NOT NULL DEFAULT 0;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_message' 
                             AND column_name='attachment_url') THEN
                    ALTER TABLE debates_message 
                    ADD COLUMN attachment_url VARCHAR(200);
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_message' 
                             AND column_name='reply_to_id') THEN
                    ALTER TABLE debates_message 
                    ADD COLUMN reply_to_id BIGINT REFERENCES debates_message(id);
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_message' 
                             AND column_name='is_flagged') THEN
                    ALTER TABLE debates_message 
                    ADD COLUMN is_flagged BOOLEAN NOT NULL DEFAULT FALSE;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_message' 
                             AND column_name='flagged_reason') THEN
                    ALTER TABLE debates_message 
                    ADD COLUMN flagged_reason VARCHAR(255) NOT NULL DEFAULT '';
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_message' 
                             AND column_name='is_hidden') THEN
                    ALTER TABLE debates_message 
                    ADD COLUMN is_hidden BOOLEAN NOT NULL DEFAULT FALSE;
                END IF;
            END $$;
            """,
            reverse_sql="-- Cannot reverse",
        ),
        migrations.RunSQL(
            """
            -- Add missing columns to debates_participation
            DO $$ 
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_participation' 
                             AND column_name='last_activity') THEN
                    ALTER TABLE debates_participation 
                    ADD COLUMN last_activity TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_participation' 
                             AND column_name='words_spoken') THEN
                    ALTER TABLE debates_participation 
                    ADD COLUMN words_spoken INTEGER NOT NULL DEFAULT 0;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_participation' 
                             AND column_name='arguments_made') THEN
                    ALTER TABLE debates_participation 
                    ADD COLUMN arguments_made INTEGER NOT NULL DEFAULT 0;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_participation' 
                             AND column_name='questions_asked') THEN
                    ALTER TABLE debates_participation 
                    ADD COLUMN questions_asked INTEGER NOT NULL DEFAULT 0;
                END IF;
            END $$;
            """,
            reverse_sql="-- Cannot reverse",
        ),
        migrations.RunSQL(
            """
            -- Add missing columns to debates_debatetopic
            DO $$ 
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name='debates_debatetopic' 
                             AND column_name='created_by_id') THEN
                    ALTER TABLE debates_debatetopic 
                    ADD COLUMN created_by_id INTEGER REFERENCES users_user(id);
                END IF;
            END $$;
            """,
            reverse_sql="-- Cannot reverse",
        ),
    ]
