# Generated by Django 4.2.23 on 2025-06-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("debates", "0014_add_reply_to_field"),
    ]

    operations = [
        # First copy data from author_id to user_id where user_id is null
        migrations.RunSQL(
            "UPDATE debates_message SET user_id = author_id WHERE user_id IS NULL AND author_id IS NOT NULL;",
            reverse_sql="UPDATE debates_message SET author_id = user_id WHERE author_id IS NULL AND user_id IS NOT NULL;",
        ),
        # Remove the author_id column
        migrations.RunSQL(
            "ALTER TABLE debates_message DROP COLUMN IF EXISTS author_id;",
            reverse_sql="ALTER TABLE debates_message ADD COLUMN author_id INTEGER;",
        ),
    ]
