# Generated by Django 4.2.23 on 2025-06-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(
                default="Notification",
                help_text="The notification title",
                max_length=255,
            ),
        ),
    ]
